on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      fail_workflow:
        description: 'Fail the workflow'
        type: boolean
        default: false

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run build
      run: |
        echo "Hello, build!"
    - name: Fail the workflow - ${{ github.event.inputs.fail_workflow }}
      if: ${{ github.event.inputs.fail_workflow == 'true' }}
      run: exit 1

    - name: disable auto-merge
      run: |
        gh pr merge --disable-auto "${{github.event.pull_request.html_url}}"
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}